apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant
  namespace: my-namespace
  annotations:
    ignore-check.kube-linter.io/required-annotation-email: Michael Foster does what he wants today.
    ignore-check.kube-linter.io/required-label-owner: Michael Foster does what he wants today.
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: compliant
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: compliant
    spec:
      serviceAccountName: my-service-account
      containers:
      - image: nginx:latest
        name: nginx 
        securityContext:
          runAsNonRoot: true
          privileged: false
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "1" 
          limits:
            memory: "4Gi"
            cpu: "2" 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: my-app
  annotations:
    team: database
    apiVersion: apps/v1