apiVersion: v1
kind: Namespace
metadata:
  name: hello
  labels:
    app: hello-world
    namespace: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello
  labels:
    app: hello-world
    deployment: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: k8s-demo
        image: nginxdemos/hello:0.2
        ports:
        - name: port
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello
  labels:
    app: hello-world
    service: hello-world
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    targetPort: 80
    port: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-role
  namespace: hello
rules:
- apiGroups:
  - extensions
  resourceNames:
  - default-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-role-binding
  namespace: hello
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: hello
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: hello
