apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-compliant
  namespace: my-namespace
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: non-compliant
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: non-compliant
    spec:
      serviceAccountName: nonexistent
      containers:
      - image: nginx:latest
        name: nginx
        env:
        - name: AWS_SECRET_KEY
          value: b2dfac006d88dd4f0b1d68f690184a09
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliant
  namespace: my-namespace
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: compliant
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: compliant
    spec:
      serviceAccountName: my-service-account
      containers:
      - image: nginx:latest
        name: nginx 
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          privileged: true
        resources:
          requests:
            memory: "1Gi"
            cpu: "1" 
          limits:
            memory: "4Gi"
            cpu: "2" 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: my-namespace
  labels:
    app.kubernetes.io/name: my-app
  annotations:
    team: database

